### ISSUE TITLE
Mouse input

### ISSUE THREAD

**Issue by kb173** [kb173/3d-asteroids#3]
Look around the cockpit with the mouse (take from previous example)

**Comment by incredibleLeitman** [comment]
first draft implemented

definition of done:
Does this have to be in the player class?
How to distinguish mouse/lockaround translations from movement per keyboard?

**Comment by kb173** [comment]
The mouse view was made more natural feeling in df2dd37.

I'd suggest moving it to a class which inherits from CameraObject, maybe MouseViewCameraObject.
